#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
    echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
    echo "good luck"
    else
    echo "Holberton School"
    fi
    ((COUNTER=COUNTER+1))
done
